######################################################################################
#                       THIS IS SAMPLE OF THE CONFIGURATION                          #
# IT'S NOT A DEFAULT CONFIGURATION, IT'S JUST A REFERENCE TO ALL OPTIONS AND PLUGINS #
#       MORE DOCS CAN BE FOUND HERE: <https://roadrunner.dev/docs/intro-config>      #
######################################################################################

# Production usage guide: https://roadrunner.dev/docs/beep-beep-production

# Hint: RR will replace any config options using reference to environment variables,
# eg.: `option_key: ${ENVIRONMENT_VARIABLE_NAME}`.

# Important: TCP port numbers for each plugin (rpc, http, etc) must be unique!

# Remote Procedures Calling (docs: https://roadrunner.dev/docs/beep-beep-rpc)
# Is used for connecting to RoadRunner server from your PHP workers.
rpc:
  # TCP address:port for listening.
  #
  # Default: "tcp://127.0.0.1:6001"
  listen: tcp://127.0.0.1:6001

# Application server settings (docs: https://roadrunner.dev/docs/php-worker)
server:
  # Worker starting command, with any required arguments.
  #
  # This option is required.
  command: "php psr-worker.php"

  # Environment variables for the worker processes.
  #
  # Default: <empty map>
  env:
    - FLOW_CONTEXT: "Production"

# Logging settings (docs: https://roadrunner.dev/docs/beep-beep-logging)
logs:
  # Logging mode can be "development", "production" or "raw". Do not forget to change this value for production environment.
  #
  # Development mode (which makes DPanicLevel logs panic), uses a console encoder, writes to standard error, and
  # disables sampling. Stacktraces are automatically included on logs of WarnLevel and above.
  #
  # Default: "development"
  mode: development

  # Logging level can be "panic", "error", "warn", "info", "debug".
  #
  # Default: "debug"
  level: debug

# HTTP plugin settings.
http:
  # Host and port to listen on (eg.: `127.0.0.1:8080`).
  #
  # This option is required.
  address: 127.0.0.1:8080

  pool:
    num_workers: 4

  # Settings for "static" middleware (docs: https://roadrunner.dev/docs/http-static).
  static:
    # Path to the directory to serve
    #
    # Default: "." (current)
    dir: "./Web"

    # File patterns to forbid
    #
    # Default: empty
    forbid: [ ".php" ]

    # Etag calculation (base on the body CRC32)
    #
    # Default: false
    calculate_etag: true

metrics:
  address: 127.0.0.1:2112

# FIXME Reload and development context is another story...
## reload:
##   # sync interval
##   interval: 1s
##   # global patterns to sync
##   patterns: [ ".php" ]
##   # list of included for sync services
##   services:
##     http:
##       # recursive search for file patterns to add
##       recursive: true
##       # ignored folders
##       ignore: [ "Packages" ]
##       # service specific file pattens to sync
##       patterns: [ ".php", ".go", ".md" ]
##       # directories to sync. If recursive is set to true,
##       # recursive sync will be applied only to the directories in `dirs` section
##       dirs: [ "." ]
##
